import './globals.css'
import LoginModal from '@/components/LoginModal'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body>
        <Navbar />
        <div className='mt-0'>
          <LoginModal />
          {children}
        </div>
      </body>
    </html>
  )
}
